2025-08-12 17:08:04,093 - ERROR - 發生錯誤
Traceback (most recent call last):
  File "C:\Users\trjhang\PycharmProjects\training\logDemo.py", line 22, in <module>
    1 / 0
    ~~^~~
ZeroDivisionError: division by zero
2025-08-12 17:15:16,839 - ERROR - 發生錯誤
Traceback (most recent call last):
  File "C:\Users\trjhang\PycharmProjects\training\logDemo.py", line 23, in <module>
    a= {[1024]:"jack"}
       ^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
2025-08-12 17:16:19,686 - ERROR - unhashable type: 'list'
Traceback (most recent call last):
  File "C:\Users\trjhang\PycharmProjects\training\logDemo.py", line 23, in <module>
    a= {[1024]:"jack"}
       ^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
2025-08-12 17:18:54,869 - ERROR - unhashable type: 'list'
Traceback (most recent call last):
  File "C:\Users\trjhang\PycharmProjects\training\logDemo.py", line 27, in <module>
    a= {[1024]:"jack"}
       ^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
2025-08-12 17:19:20,786 - ERROR - 發生錯誤
Traceback (most recent call last):
  File "C:\Users\trjhang\PycharmProjects\training\logDemo.py", line 27, in <module>
    a= {[1024]:"jack"}
       ^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
2025-08-12 17:19:35,226 - ERROR - 發生錯誤
Traceback (most recent call last):
  File "C:\Users\trjhang\PycharmProjects\training\logDemo.py", line 27, in <module>
    a= {[1024]:"jack"}
       ^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
2025-08-12 17:19:40,461 - ERROR - 發生錯誤
Traceback (most recent call last):
  File "C:\Users\trjhang\PycharmProjects\training\logDemo.py", line 27, in <module>
    a= {[1024]:"jack"}
       ^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
2025-08-15 13:49:32,666 - ERROR - 發生錯誤
Traceback (most recent call last):
  File "C:\Users\trjhang\PycharmProjects\forTraining\logDemo.py", line 27, in <module>
    a= {[1024]:"jack"}
       ^^^^^^^^^^^^^^^
TypeError: unhashable type: 'list'
